<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UAssetAPI" HintPath="$(RepoRoot)lib/UAssetAPI/UAssetAPI.dll" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
    <EmbeddedResource Include="seed.uasset" LogicalName="seed.uasset" />
    <EmbeddedResource Include="seed.uexp" LogicalName="seed.uexp" />
  </ItemGroup>
</Project>
